IBX-7611: Bump version for webpack and sass-loader
ibexa/recipes-dev pull request #108
Opened 2024-01-24 11:04 UTC by lucasOsti

Bump version for 
 - @symfony/webpack-encore ^1.7.0 -> ^3.0.0
 - sass-loader ^12.5.0 -> ^13.0.0

2024-01-24 11:26 UTC, glye approved these changes

2024-01-24 16:12 UTC, GrabowskiM approved these changes

2024-01-25 07:37 UTC, adamwojs approved these changes

2024-01-29 13:17 UTC, dew326 commented on ibexa/content/4.5/encore/package.json
> +    "@symfony/webpack-encore": "^3.0.0",
Why we are changing it for 4.5 in content but not for other editions?

2024-01-31 06:23 UTC, dew326 requested changes

2024-01-31 06:23 UTC, dew326 commented on ibexa/experience/4.6/encore/package.json
> +    "@symfony/webpack-encore": "^3.0.0",
missing sass-loader change

2024-01-31 08:46 UTC, dew326 approved these changes

2024-01-31 09:44 UTC, glye commented
@lucasOsti Ready for QA?

2024-01-31 09:46 UTC, glye requested changes
Oh BTW I just noticed the target is master, this should go into 4.5

2024-01-31 09:57 UTC, lucasOsti commented
Here we only have branch master but in this PR I edited files for version 4.5 e.g https://github.com/ibexa/recipes-dev/pull/108/files#diff-b602eecefcd395939d9c80eec7bc0f8a40fbc0d53a52537e12d7e81415dff1baL2

2024-01-31 10:00 UTC, glye approved these changes
D'oh 😅

2024-02-21 11:31 UTC, micszo approved these changes
Installed and tested on 4 editions of 4.5 and 4.6.

2024-02-22 11:51 UTC, merged