Added prepend encore function
ibexa/recipes-dev pull request #19
Opened 2022-08-09 08:07 UTC by GrabowskiM

2022-08-09 08:20 UTC, dew326 requested changes

2022-08-09 08:20 UTC, dew326 commented on ibexa/commerce/4.2/encore/ibexa.webpack.config.manager.js
> +    const config = ibexaConfig ? ibexaConfig : eZConfig;
as this is a new method do we need to care about accepting eZConfig as a parameter, I don't think so.

2022-08-09 08:23 UTC, dew326 commented
This is something we should document so summon @DominikaK

2022-08-09 08:34 UTC, dew326 requested changes

2022-08-09 08:34 UTC, dew326 commented on ibexa/oss/4.2/encore/ibexa.webpack.config.manager.js
> +const prepend = ({ ibexaConfig, eZConfig, entryName, newItems }) => {
```suggestion
const prepend = ({ ibexaConfig, entryName, newItems }) => {
```

2022-08-09 08:34 UTC, dew326 commented on ibexa/experience/4.2/encore/ibexa.webpack.config.manager.js
> +const prepend = ({ ibexaConfig, eZConfig, entryName, newItems }) => {
```suggestion
const prepend = ({ ibexaConfig, entryName, newItems }) => {
```

2022-08-09 08:34 UTC, dew326 commented on ibexa/commerce/4.2/encore/ibexa.webpack.config.manager.js
> +const prepend = ({ ibexaConfig, eZConfig, entryName, newItems }) => {
```suggestion
const prepend = ({ ibexaConfig, entryName, newItems }) => {
```

2022-08-09 08:58 UTC, dew326 approved these changes

2022-08-09 11:01 UTC, tischsoic approved these changes

2022-08-09 11:22 UTC, lucasOsti approved these changes

2023-05-31 09:55 UTC, GrabowskiM commented
Not needed currently, so it would be dead code. If needed in future, it can be reimplemented

2023-05-31 09:55 UTC, closed without merging