IBX-4962: React app blocks configuration
ibexa/recipes-dev pull request #64
Opened 2023-04-06 23:50 UTC by Gengar-i

| Question                                  | Answer |
| ---------------------------------------- | ------------------ |
| **JIRA issue**                          | [IBX-4962](https://issues.ibexa.co/browse/IBX-4962) |
| **Requires**                            | ibexa/corporate-account#154
| **Type**                                   | feature |
| **Target Ibexa version** | `v4.5` |
| **BC breaks**                          | no |

Implemented React app blocks configuration

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Checked that target branch is set correctly (main for features, the oldest supported for bugs).

2023-04-11 08:49 UTC, lucasOsti requested changes

2023-04-11 08:49 UTC, lucasOsti commented on ibexa/oss/4.5/encore/webpack.config.js
> +// React Blocks javascript
```suggestion
```

2023-04-12 06:18 UTC, dew326 requested changes

2023-04-12 06:18 UTC, dew326 commented on ibexa/oss/4.5/assets/js/react.blocks.js
> +import React from 'react';
page-builder is not part of the OSS edition, it should be added to all relevant editions.

2023-04-12 08:51 UTC, dew326 approved these changes

2023-04-12 08:56 UTC, lucasOsti approved these changes

2023-04-17 10:51 UTC, merged